INSERT INTO article VALUES
('1','Pentingnya Pemberian Vaksin Campak','http://10.0.2.2/anmp/img/ARTIKEL/1/1.jpg','Ini Alasan Pentingnya Pemberian Vaksin Campak Pada Anak: Yang pertama adalah Mencegah penyebaran penyakit campak. Kedua, Mencegah komplikasi yang serius. Ketiga, Membantu mencapai herd immunity. Keempat, Vaksin campak aman dan efektif. Campak termasuk penyakit menular, karenanya penting untuk melakukan vaksin campak pada anak sebagai langkah pencegahan.',1),
('2','Waspada, Ini 4 Gangguan Kesehatan Akibat Heat Stroke','http://10.0.2.2/anmp/img/ARTIKEL/2/2.jpg','Heat stroke merupakan masalah kesehatan yang terjadi ketika seseorang terpapar cuaca panas yang ekstrem. Kondisi ini dapat menimbulkan komplikasi misalnya ARDS, gangguan pada otak seperti pingsan dan pembengkakan otak, gagal ginjal, dan kematian.',2),
('3','3 Tanda Holiday Blues setelah Libur Lebaran','http://10.0.2.2/anmp/img/ARTIKEL/3/3.jpg','Libur Lebaran sudah berakhir, saatnya kembali ke rutinitas harian. Namun, waspada tanda-tanda holiday blues setelah libur Lebaran yang mungkin terjadi. Tanda Holiday Blues : Mengalami rasa cemas berlebihan, Kehilangan motivasi untuk melakukan kegiatan, Perubahan suasana hati menjadi lebih buruk',3),
('4','Cara Menghitung SPF dalam Penggunaan Sunscreen','http://10.0.2.2/anmp/img/ARTIKEL/4/4.jpg','Setiap orang perlu tahu cara menghitung SPF yang diberikan pada sunscreen, untuk mendapatkan perlindungan dari sinar matahari dan mencegah risiko kanker kulit akibat sinar UV. Tingkat perlindungan dari sunscreen: Rendah SPF dibawah 15, Sedang SPF 15-29, Tinggi SPF 30-49, Sangat tinggi SPF lebih dari 50.',4),
('5','Begini Cara Merawat Mata dengan Pola Makan Sehat','http://10.0.2.2/anmp/img/ARTIKEL/5/5.jpg','Pola makan sehat bisa menjadi salah satu cara merawat mata. Misalnya dengan mengonsumsi ikan, sayuran berdaun hijau, dan buah-buahan segar. Cara Merawat Mata dengan Konsumsi Makanan Sehat Untuk merawat kesehatan mata, membutuhkan banyak jenis antioksidan. Seperti lutein, zeaxanthin, vitamin A, C dan E, beta karoten, asam lemak omega-3, dan zink.',5),
('6','Cegah Stres, Ini 5 Cara Menyikapi Pasangan yang Selingkuh','http://10.0.2.2/anmp/img/ARTIKEL/6/6.jpg','Selingkuh adalah masalah besar yang dapat berujung pada berakhirnya hubungan begitu saja dan menyebabkan stres. Kamu bisa menyikapinya dengan meminta bantuan dari ahlinya. Cara menyikapi : Menerima Perasaan Sendiri, Jangan Menyalahkan Diri Sendiri, Jangan Melakukan Balas Dendam, Lebih Merawat dan Memperhatikan Diri Sendiri, dan Jangan Saling Menyalahkan.',6),
('7','Jarang Diketahui, Ini 6 Penyebab Jari Tangan Bengkak','http://10.0.2.2/anmp/img/ARTIKEL/7/7.jpg','Jari tangan bengkak disebut juga di dunia medis dengan daktilis, yaitu kondisi yang terjadi ketika air tertahan di bagian jari tangan atau kaki sehingga menyebabkan pembengkakan. Kondisi fisik terjadi sebagai gejala penyakit lain yang lebih serius. Contohnya: Arthritis atau radang sendi, AutoImun, TBC, Sifilis, Infeksi bakteri, dan alergi.',7),
('8','Orang Tua Mengidap Gangguan Narsistik, Ini Dampak pada Anak','http://10.0.2.2/anmp/img/ARTIKEL/8/8.jpg','Pola asuh orang tua akan sangat berpengaruh kepada kondisi mental anak saat tumbuh besar. Orang tua yang memiliki gangguan narsistik akan cenderung menyebabkan masalah kepercayaan diri pada anak. Dampak: Rasa percaya diri yang rendah, Sulit mengekspresikan diri, Menjadi people-pleaser',8);

INSERT INTO Doctor VALUES
('1','Dr. dr. Joni Wahyuhadi, Sp.BS','http://10.0.2.2/anmp/img/DOKTER/doc1.jpg','Dr. dr. Joni Wahyuhadi, Sp.BS adalah anggota dari Surabaya Neuroscience Institute (SNeI). Dokter Joni lulus menjadi dokter spesialis bedah saraf pada tahun 2000 setelah menyelesaikan pendidikan spesialisnya di Universitas Airlangga Surabaya. Dokter Joni melanjutakan gelar Doktoralnya di Universitas Airlangga dan lulus pada tahun 2010.','Senin-Rabu','09.00-14.00',1),
('2','dr. Inggriani Tobarasi, Sp.A, M.Kes','http://10.0.2.2/anmp/img/DOKTER/doc2.jpg','dr. Inggriani Tobarasi, Sp.A, M.Kes adalah dokter poli anak yang telah menempuh pendidikan S1 di Fakultas Kedokteran Universitas Indonesia lulus pada tahun 2002 dan S2 di Fakultas Kedokteran Universitas Sriwijaya lulus pada tahun 2012.','Senin-Sabtu','10.00-14.00',2),
('3','dr. Tedy Apriawan, Sp.BS','http://10.0.2.2/anmp/img/DOKTER/doc3.jpg','dr. Tedy Apriawan, Sp.BS adalah salah satu anggota dari Surabaya Neuroscience Institute (SNeI). Dokter Tedy lulus menjadi dokter spesialis bedah saraf pada tahun 2013 setelah dokter Tedy menyelesaikan pendidikan spesialisnya di Universitas Airlangga Surabaya.','Senin dan Selasa','13.00-17.00',3),
('4','dr. Rika Andriani, Sp.M','http://10.0.2.2/anmp/img/DOKTER/doc4.jpg','dr. Rika Andriani, Sp.M adalah dokter poli mata yang telah menempuh pendidikan S1 di Fakultas Kedokteran Universitas Trisakti, lulus tahun 2011 dan S2 di Pendidikan Dokter Spesialis Mata Universitas Padjadjaran, lulus tahun 2018.','Senin - Sabtu','09.00-16.00',4),
('5','dr. Ananda Haris, Sp.BS','http://10.0.2.2/anmp/img/DOKTER/doc5.jpg','dr. Ananda Haris, Sp.BS adalah salah satu anggota dari Surabaya Neuroscience Institute (SNeI). Dokter Haris lulus menjadi dokter spesialis bedah saraf pada tahun 2007 setelah dokter Wihasto menyelesaikan pendidikan spesialisnya di Universitas Airlangga Surabaya.','Senin dan Rabu','09.00-15.00',5),
('6','dr. Putri Yeantesa, SpJP-FIHA','http://10.0.2.2/anmp/img/DOKTER/doc6.jpg','dr. Putri Yeantesa, SpJP-FIHA adalah dokter poli jantung yang telah menempuh pendidikan S1 dan S2 di  Universitas andalas pada tahun 2009 dan 2019.','Selasa-Jumat','15.00-18.00',6),
('7','Dr. dr. Rahadian Indarto Susilo, Sp.BS','http://10.0.2.2/anmp/img/DOKTER/doc7.jpg','Dr. dr. Rahadian Indarto Susilo, Sp.BS adalah anggota dari Surabaya Neuroscience Institute (SNeI). Dokter Rahadian lulus menjadi dokter spesialis bedah saraf pada tahun 2009 setelah menyelesaikan pendidikan spesialis di Universitas Airlangga, melanjutakan gelar Doktoralnya di Universitas Airlangga dan lulus pada tahun 2019 hingga memiliki sub spesialis divisi Neuro Onkology / Tumor Otak.','Kamis-Sabtu','07.00-11.00',7),
('8','dr. Gina Frances Agustine Rotty, Sp.OG','http://10.0.2.2/anmp/img/DOKTER/doc8.jpg','dr. Gina Frances Agustine Rotty, Sp.OG adalah dokter klinik Kebidanan dan Penyakit Kandungan yang telah menempuh pendidikan Dokter Umum di Fakultas Kedokteran Universitas Sam Ratulangi tahun 1992 dan Dokter Spesialis Obstetri Ginekologi di Fakultas Kedokteran Universitas Sam Ratulangi tahun 2005.','Rabu-Sabtu','12.00-14.00',8);

INSERT INTO drug VALUES
('1','Rhinos Junior Sirup 60 ml','http://10.0.2.2/anmp/img/OBAT/drug1.jpg','RHINOS JUNIOR merupakan obat dengan kandungan Pseudoephedrine HCl dan Chlorpheniramine Maleate yang digunakan untuk meringankan gejala flu seperti bersin-bersin dan hidung tersumbat karena pilek.','Dewasa dan anak-anak lebih dari 12 tahun: 2 sendok takar (10 ml), 3 kali sehari. Anak-anak 6-12 tahun: 1 sendok takar (5 ml), 3 kali sehari. Anak-anak 2-5 tahun: 1/2 sendok takar (2.5 ml), 3 kali sehari. Anak-anak di bawah 2 tahun: atas petunjuk dokter.','44.200',1),
('2','Dextamine 10 Tablet','http://10.0.2.2/anmp/img/OBAT/drug2.jpg','DEXTAMINE merupakan obat dengan kandungan Dexamethasone (glukokortikoid) dan Dexchlorpheniramine Maleate. Obat ini bekerja sebagai antiinflamasi, antirematik, serta antialergi/antihistamin. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.','PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 1 tablet, 3 kali per hari. Anak : 1/2 tablet, 3 kali per hari.','23.600',2),
('3','Counterpain Cream 30 g + Counterpain Cool Gel 15 g','http://10.0.2.2/anmp/img/OBAT/drug3.jpg','Counterpain Cream: Membantu meredakan nyeri pada otot, sendi, nyeri, keseleo dan encok. Counterpain Cool Gel: Digunakan untuk meredakan nyeri otot dan nyeri sendi yang berhubungan dengan terkilir, memar dan cedera pada saat olahraga.','Sesuai kebutuhan.','44.700',3),
('4','FG Troches 10 Tablet','http://10.0.2.2/anmp/img/OBAT/drug4.jpg','FG TROCHES merupakan tablet hisap Antibiotik yang memiliki kandungan Fradiomycin Sulfate dan Gramicidin-S HCl yang berfungsi untuk mengobati gingivitis, stomatitis, faringitis, bronkitis, tonsilitis, angina vincent, difteri faringeal, priodontitis. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.','PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa: 1 - 2 tablet, dihisap 4 - 5 kali perhari. Anak-anak : 1 tablet, dihisap 4 - 5 kali perhari.','13.300',4),
('5','Bioplacenton Gel 15 g','http://10.0.2.2/anmp/img/OBAT/drug5.jpg','BIOPLACENTON merupakan obat yang mengandung Placenta Extract dan Neomycin sulfate dan digunakan untuk mengobati luka bakar, infeksi, kronik dll yang bekerja memicu pembentukan jaringan baru dan untuk wound healing, serta mencegah/mengatasi infeksi bakteri area luka.','PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Oleskan 4-6 x sehari atau sesuai kebutuhan pada area luka.','34.100',5),
('6','Cendo Xitrol Eye Drop 5 ml','http://10.0.2.2/anmp/img/OBAT/drug6.jpg','CENDO XITROL adalah tetes mata steril yang mengandung Deksametason, Neomycin Sulfate, Poliymyxin B Sulfate yang diindikasikan untuk kondisi inflamasi mata yang responsif terhadap steroid disertai infeksi bakteri/adanya reaksi infeksi mata karena bakteri.','PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. 1-2 tetes tiap jam (siang), dan tiap 2 jam (malam). jika respon baik dikurangi menjadi 1 tetes/4 jam. Untuk mengontrol gejala, dosis dikurangi 3-4x sehari 1 tetes.','38.800',6),
('7','Betadine Throat Spray 50 ml','http://10.0.2.2/anmp/img/OBAT/drug7.jpg','BETADINE THROAT SPRAY merupakan spray mulut dengan kandungan Povidone Iodine 0.45%. Produk ini dapat membantu meredakan sakit tenggorokan, sariawan, gusi bengkak, bau mulut dan nafas tidak segar.','1x semprot, gunakan 3 kali per hari.','140.700',7),
('8','Promag Suspensi 60 ml','http://10.0.2.2/anmp/img/OBAT/drug8.jpg','PROMAG merupakan obat sakit maag yang mengandung Hydrotalcite, Magnesium Hydroxide, dan Simethicone. Obat ini diigunakan untuk meringankan gejala sakit maag akibat kelebihan asam lambung seperti perih, mual, kembung, dan nyeri ulu hati.','Dewasa : 1-2 sendok takar (5-10 ml), 3-4 kali sehari. Anak usia 6-12 tahun : 1 sendok takar (5 ml), 3-4 kali sehari.','14.600',8);

INSERT INTO Facility VALUES
('1','Donasi Sesama','http://10.0.2.2/anmp/img/FASILITAS/f1.jpg','Dengan Donasi Semua Teratasi',1),
('2','Konsultasi Dokter','http://10.0.2.2/anmp/img/FASILITAS/f2.jpg','Konsultasikan Pada Ahlinya',2),
('3','Kalender Menstruasi','http://10.0.2.2/anmp/img/FASILITAS/f3.jpg','Cek Tanggal Menstruasimu',3),
('4','Opname Service','http://10.0.2.2/anmp/img/FASILITAS/f4.jpg','Rawat Inaplah Bersama Kami',4),
('5','Gymnastic With Us','http://10.0.2.2/anmp/img/FASILITAS/f5.jpg','Olahraga Agar Badan Terjaga',5),
('6','Blood Donor','http://10.0.2.2/anmp/img/FASILITAS/f6.jpg','Mulai Donorkan Darahmu Sekarang',6);

